name: CurseForge Localizations
description: Uploads localization strings found in Lua files to CurseForge
branding:
  icon: type
  color: yellow
inputs:
  project_id:
    description: Project ID on CurseForge
  base_lang:
    description: Base language of strings
    default: enUS
  handle_missing:
    description: How to handle missing phrases
    default: DoNothing
  namespace:
    description: Namespace to upload to
  exclude:
    description: List of file patterns to exclude
  string_pattern:
    description: Custom regex pattern to use
runs:
  using: composite
  steps:
    - name: Install Python 3.13+
      uses: actions/setup-python@v6
      id: python
      with:
        python-version: '>=3.13'
        update-environment: false
        cache: 'pip'
    - name: Install dependencies
      shell: bash
      env:
        PYTHON_PATH: ${{ steps.python.outputs.python-path }}
      run: pip install -r "$GITHUB_ACTION_PATH/requirements.txt"
    - name: Run script
      shell: bash
      run: |
        ${{ steps.python.outputs.python-path }} "${{ github.action_path }}/update.py" \
          --id "${{ inputs.project_id }}" \
          --lang "${{ inputs.base_lang }}" \
          --missing "${{ inputs.handle_missing }}" \
          --namespace "${{ inputs.namespace }}" \
          --pattern "${{ inputs.string_pattern }}" \
          --exclude "${{ inputs.exclude }}"
