name: CurseForge Localizations
description: Uploads localization strings found in Lua files to CurseForge
branding:
  icon: type
  color: yellow
inputs:
  project_id:
    description: Project ID on CurseForge
  base_lang:
    description: Base language of strings
    default: enUS
  handle_missing:
    description: How to handle missing phrases
    default: DoNothing
  namespace:
    description: Namespace to upload to
  exclude:
    description: List of file patterns to exclude
runs:
  using: composite
  steps:
    - name: Install Python 3.13+
      uses: actions/setup-python@v6
      with:
        python-version: '>=3.13'
    - name: Install dependencies
      shell: bash
      run: pip install -r "${{ github.action_path }}/requirements.txt"
    - name: Run script
      shell: bash
      run: |
        args=()
        [ -n "${{ inputs.project_id }}" ] && args+=(--id "${{ inputs.project_id }}")
        [ -n "${{ inputs.base_lang }}" ] && args+=(--lang "${{ inputs.base_lang }}")
        [ -n "${{ inputs.handle_missing }}" ] && args+=(--missing "${{ inputs.handle_missing }}")
        [ -n "${{ inputs.namespace }}" ] && args+=(--namespace "${{ inputs.namespace }}")
        while read -r exclude; do
          args+=(--exclude "$exclude")
        done < <(echo "${{ inputs.exclude }}" | head -c -1)
        python3 "${{ github.action_path }}/update.py" "${args[@]}"
